# Generated by Django 4.2 on 2023-05-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
